// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hepwjkeelvwqffqvyloa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlcHdqa2VlbHZ3cWZmcXZ5bG9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY5ODk3NzMsImV4cCI6MjA5MjU2NTc3M30.i8dHCvfMyPJ5_AwPk_7nhCD5eGwIiQbWH_-kDeBmt_Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});